### PR TITLE
feat: custom karma-safari-launcher

### LINKED ISSUE #26: Update to the latest karma-safari-tech-preview-launcher
It's two major versions ahead, so we need to determine if that matters or not.

### PR DESCRIPTION
**Pull request by brandonocasey**
See:
https://github.com/BrandonOCasey/karma-safari-applescript-launcher
https://github.com/karma-runner/karma-safari-launcher/issues/29

Closes #26

### CODE REVIEW

**Review by misteroneill — DISMISSED** [review]

**Comment by brandonocasey** [comment]
~~This still does not appear to work for me, hmmm~~ Fixed.

**Comment by misteroneill** [comment]
It's not working for me because it's missing the `applescript` module:

```
videojs-generate-karma-config@5.1.0 /Users/poneill/dev/videojs-generate-karma-config
├── @videojs/generator-helpers@1.0.0
├── UNMET PEER DEPENDENCY karma@*
├── karma-browserstack-launcher@1.4.0
├── karma-chrome-launcher@2.2.0
├── karma-coverage@1.1.2
├── karma-detect-browsers@2.3.3
├── karma-firefox-launcher@1.1.0
├── karma-ie-launcher@1.0.0
├── karma-qunit@2.1.0
├── karma-safari-launcher@1.0.0 -> /Users/poneill/dev/videojs-generate-karma-config/karma-safari-launcher
├── karma-static-server@1.0.0
├── karma-teamcity-reporter@1.1.0
├── qunit@2.9.2
├── videojs-generator-verify@1.2.0
└── videojs-standard@8.0.2

npm ERR! peer dep missing: karma@*, required by videojs-generate-karma-config@5.1.0
npm ERR! peer dep missing: karma@>=0.9, required by karma-browserstack-launcher@1.4.0
npm ERR! peer dep missing: karma@>=0.9, required by karma-ie-launcher@1.0.0
npm ERR! peer dep missing: karma@>=0.9, required by karma-teamcity-reporter@1.1.0
npm ERR! missing: applescript@1.0.0, required by karma-safari-launcher@1.0.0
```

**Comment by gkatsev** [comment]
`file:` dep in a published package likely doesn't trigger an install in it, we'd want to either add a postinstall script that runs `npm i` in the directory or just move the applescript dep up.

**Review by misteroneill — APPROVED** [review]
It works!

**Pull request merged**
